# -*- coding: utf-8 -*-
"""JSON

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfjK_kFDRjXJaKZxkPwwN6pbXnYu7kzu
"""

with open('/content/drive/MyDrive/Prog2/mammals.json', 'r') as f:
    mammals = json.load(f)

def totalEspecies(mammals):
    if 'children' not in mammals:
        return 1
    count = 0
    for child in mammals['children']:
        count += totalEspecies(child)
    return count



def gatos(dict):
  if dict['name'] == 'Felidae':
    return dict
  if 'children' in dict:
    for c in dict['children']:
      r = gatos(c)
      if r != None: return r
    return None

def filhos(d, dict):
    nome = dict['name']
    cs = dict.get('children', [])
    d[nome] = [c['name'] for c in cs]
    for c in cs:
        filhos(d, c)
    return d

def desenhaGatos(cat_dict):
    dot_code = "graph G {\n"
    dot_code += "  layout=twopi;\n"
    dot_code += "  ranksep=4;\n"
    dot_code += "  ratio=auto;\n"
    dot_code += '  node [fontcolor="purple", fontsize=20, shape=plaintext];\n'
    dot_code += '  edge [color="gray", penwidth=2];\n\n'

    def write_nodes_and_edges(parent, children):
        nonlocal dot_code

        dot_code += f'  "{parent}" [label="{parent}"];\n'
        for child in children:
            dot_code += f'  "{parent}" -- "{child}";\n'
            if child in cat_dict:
                write_nodes_and_edges(child, cat_dict[child])

    root = list(cat_dict.keys())[0]
    write_nodes_and_edges(root, cat_dict[root])

    dot_code += "}"

    with open("gatos.dot", "w") as file:
        file.write(dot_code)

# Call the function with your dictionary
filhosGatos = {}
dict_mamifero = filhos(filhosGatos, gatos(mammals))
desenhaGatos(dict_mamifero)